# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  before_all do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "~/Documents/appstoreconnect/AuthKey_G3.p8",
      duration: 1200,
      in_house: false
    )
  end

  desc "Uygulamayı TestFlight'a gönderir"
  lane :deploy do
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Runner.xcodeproj"
    )
    
    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
