import '../services/global_settings.dart';

final Map<String, Map<String, String>> dictionary = {
  'tr': {
    'app_name': 'Kuran Günlüğü',
    'slogan': 'Huzurla Oku',
    'splash_text': 'Bunlar hikmet dolu\nKitabın ayetleridir.',
    'today_ayah': 'GÜNÜN AYETİ',
    'save': 'Kaydet',
    'saved': 'Listemde',
    'share': 'Paylaş',
    'listen': 'Dinle',
    'stop': 'Durdur',
    'list_title': 'Listem',
    'list_empty': 'Henüz kaydedilmiş bir ayet yok.',
    'settings_title': 'Ayarlar',
    'language': 'Dil',
    'font_size': 'Yazı Boyutu',
    'size_small': 'Küçük',
    'size_medium': 'Orta',
    'size_large': 'Büyük',
    'added_msg': 'Listene kaydedildi ✅',
    'removed_msg': 'Listeden çıkarıldı',
    'premium_locked': 'Geçmiş Kilitli',
    'premium_desc': 'Daha eskiye gitmek için\nPremium üye olmalısınız.',
    'get_premium': "PREMIUM'A GEÇ",
    'go_today': 'Bugüne Dön',
    'prem_title': 'Premium Üyelik',
    'prem_active': 'Premium Üye 👑',
    'share_loading': 'Görüntü hazırlanıyor...',
    'prem_f1': 'Reklamsız Deneyim',
    'prem_f2': 'Sınırsız Geçmişe Erişim',
    'prem_f3': 'Özel Yazı Tipleri',
    'prem_f4': 'Geliştiriciye Destek',
    'prem_price': 'Yıllık Sadece 199.99 ₺',
    'prem_btn': 'ABONE OL',
    'prem_success': 'Tebrikler! Artık Premiumsunuz 🎉',
    'notif_title': 'Hayırlı Sabahlar ☀️',
    'notif_body': 'Bugünün ayeti seni bekliyor. Okumak ister misin?',
    'test_msg': 'Bildirimler başarıyla çalışıyor! 🚀',
    'note_title': 'Günlük Notum 📝',
    'note_hint': 'Bu ayet sana ne hissettirdi?',
    // ignore: equal_keys_in_map
    'save': 'Kaydet',
    'your_note': 'Notun:',
    'my_note': 'Notum:',
    'add_note': 'Not Ekle',
    'edit_note': 'Notu Düzenle',
    'notif_active': 'Bildirimler Aktif ✅',
    'notif_inactive': 'Bildirimler Kapalı 🔕',
    'notif_active_desc': 'Her gün ayetiniz cebinizde.',
    'notif_inactive_desc':
        'Günün ayetini kaçırmamak için lütfen bildirimleri açın.',
    'turn_on': 'AÇ',
    'reciter_title': 'Seslendiren Hafız',
    'selected_reciter': 'Seçili Hafız',
    'select_reciter_title': 'Hafız Seçimi',
    'support_us': 'Projeye Destek Ol',
    'support_desc': 'Uygulamanın gelişmesi için katkıda bulunabilirsiniz.',
    'donate': 'Bağış Yap',
    'donation_success': 'Teşekkürler!',
    'donation_success_msg': 'Desteğiniz için Allah razı olsun.',
    'donation_error': 'Bir hata oluştu veya iptal edildi.',
    'loading_products': 'Bağış seçenekleri yükleniyor...',
    'no_products': 'Şu anda bağış seçeneği bulunmuyor.',
    'support_title': 'Bu Hayra Ortak Olun',
    'support_long_desc':
        'Kuran Günlüğü uygulamasını tamamen ücretsiz ve reklamsız olarak geliştirmeye devam ediyoruz. Bu projenin sürekliliğini sağlamak ve geliştirilmesine katkıda bulunmak isterseniz bize destek olabilirsiniz.',
    'support_footer':
        'Desteğiniz, sunucu masrafları ve uygulamanın geliştirilmesi için kullanılacaktır.',
    'donation_tier_1': 'Uygulamaya Destek',
    'donation_tier_2': 'Projeye Destek',
    'donation_tier_3': 'Geliştirmeye Destek',
    'donation_tier_default': 'Destek Ol',
    'success_title': 'Teşekkürler',
    'success_body':
        'Desteğiniz bizim için çok değerli. Katkılarınızla uygulamayı geliştirmeye devam edeceğiz.',
    'secure_payment': 'Güvenli Ödeme & Gizli Bağış',
    'support_gold_subtitle': 'Bu hayra ortak olun ✨',
    'prayer_method_title': 'Namaz Vakti Hesaplama Yöntemi',
    'prayer_method_subtitle': 'Hangi otoriteyi kullanmak istersiniz?',
    'prayer_method_auto': 'Otomatik (Önerilen)',
    'prayer_method_auto_desc': 'Konumunuza göre seçilir',
    'prayer_method_turkey': 'Türkiye (Diyanet)',
    'prayer_method_mwl': 'Dünya İslam Birliği (Avrupa/Küresel)',
    'prayer_method_isna': 'Kuzey Amerika (ISNA)',
    'prayer_method_makkah': 'Mekke (Ümmül-Kura)',
    'prayer_method_egypt': 'Mısır (Jeoloji Otoritesi)',
    // Prayer Times Localization
    'prayer_fajr': 'İmsak',
    'prayer_sunrise': 'Güneş',
    'prayer_dhuhr': 'Öğle',
    'prayer_asr': 'İkindi',
    'prayer_maghrib': 'Akşam',
    'prayer_isha': 'Yatsı',
    'time_remaining_sahur': 'SAHURA KALAN SÜRE',
    'time_remaining_iftar': 'İFTARA KALAN SÜRE',
    'time_remaining_sunrise': 'GÜNEŞİN DOĞUŞUNA',
    'time_remaining_general': 'VAKTİNE KALAN',
    // Prayer Times
    'prayer_times_title': 'İmsakiye - Namaz Vakitleri', // Used during Ramadan
    'prayer_times_title_regular': 'Namaz Vakitleri', // Used outside Ramadan
    'table_date': 'Tarih',
    'loading': 'Yükleniyor...',
    'location_default': 'Konumunuz',
    // Prayer Notification Settings
    'prayer_notif_toggle': 'Namaz vakti hatırlatıcıları',
    'prayer_notif_desc': 'Her namaz vaktinden 15 dakika önce bildirim',
    'prayer_notif_fajr': 'Sabah namazına 15 dakika kaldı 🕌',
    'prayer_notif_dhuhr': 'Öğle namazına 15 dakika kaldı 🕌',
    'prayer_notif_asr': 'İkindi namazına 15 dakika kaldı 🕌',
    'prayer_notif_maghrib': 'Akşam namazına 15 dakika kaldı 🕌',
    'prayer_notif_isha': 'Yatsı namazına 15 dakika kaldı 🕌',
    'prayer_notif_test': 'Test Bildirimi Gönder',
    'prayer_notif_test_sent': '✅ Test bildirimi 5 saniye sonra gelecek!',
    // Reminders Section
    'reminders_section': 'Hatırlatıcılar',
    'verse_notif_toggle': 'Günlük Ayet Hatırlatıcıları',
    'prayer_notif_title': 'Namaz Vakti Hatırlatıcıları',
    // Prayer Times Disclaimer (About Section)
    'disclaimer_title': 'Namaz Vakitleri & Yasal Uyarı',
    'disclaimer_content':
        'Namaz vakitleri, cihazınızın konumu (GPS) kullanılarak astronomik hesaplamalarla anlık üretilir. Türkiye için Diyanet İşleri Başkanlığı kriterleri (Temkin süreleri) esas alınmıştır.\n\nUyarı: Matematiksel hesaplama ve coğrafi farklar nedeniyle vakitlerde ±1-2 dakikalık sapmalar olabilir. İbadetlerinizde (özellikle İmsak ve İftar) temkinli olmak adına yerel ezan sesini veya cami vakitlerini teyit etmeniz tavsiye edilir.\n\nGizlilik: Konum veriniz sadece vakit hesaplaması için cihazınızda işlenir; sunucularımıza kaydedilmez veya paylaşılmaz.',
  },
  'en': {
    'app_name': 'Quran Diary',
    'slogan': 'Read with Peace',
    'splash_text': 'These are verses of the\nWise Book.',
    'today_ayah': 'VERSE OF THE DAY',
    'save': 'Save',
    'saved': 'Saved',
    'share': 'Share',
    'listen': 'Listen',
    'stop': 'Stop',
    'list_title': 'My List',
    'list_empty': 'No saved verses yet.',
    'settings_title': 'Settings',
    'language': 'Language',
    'font_size': 'Font Size',
    'size_small': 'Small',
    'size_medium': 'Medium',
    'size_large': 'Large',
    'added_msg': 'Saved to your list ✅',
    'removed_msg': 'Removed from list',
    'premium_locked': 'History Locked',
    'premium_desc': 'You need Premium membership\nto go further back.',
    'get_premium': 'GET PREMIUM',
    'go_today': 'Go to Today',
    'prem_title': 'Premium Membership',
    'prem_active': 'Premium Member 👑',
    'share_loading': 'Preparing image...',
    'prem_f1': 'Ad-Free Experience',
    'prem_f2': 'Unlimited History Access',
    'prem_f3': 'Custom Fonts',
    'prem_f4': 'Support Development',
    'prem_price': 'Yearly Only \$19.99',
    'prem_btn': 'SUBSCRIBE NOW',
    'prem_success': 'Congrats! You are Premium 🎉',
    'notif_title': 'Good Morning ☀️',
    'notif_body': 'Verse of the day is ready. Would you like to read?',
    'test_msg': 'Notifications work perfectly! 🚀',
    'note_title': 'My Daily Note 📝',
    'note_hint': 'How did this verse make you feel?',
    // ignore: equal_keys_in_map
    'save': 'SAVE',
    'your_note': 'Your Note:',
    'my_note': 'My Note:',
    'add_note': 'Add Note',
    'edit_note': 'Edit Note',
    'notif_active': 'Notifications Active ✅',
    'notif_inactive': 'Notifications Off 🔕',
    'notif_active_desc': 'Daily verse is in your pocket.',
    'notif_inactive_desc':
        'Please turn on notifications to not miss the daily verse.',
    'turn_on': 'TURN ON',
    'reciter_title': 'Reciter',
    'selected_reciter': 'Selected Reciter',
    'select_reciter_title': 'Select Reciter',
    'support_us': 'Support the Project',
    'support_desc': 'You can contribute to the development of the app.',
    'donate': 'Donate',
    'donation_success': 'Thank You!',
    'donation_success_msg': 'May Allah bless you for your support.',
    'donation_error': 'An error occurred or cancelled.',
    'loading_products': 'Loading donation options...',
    'no_products': 'No donation options available right now.',
    'support_title': 'Support the Cause',
    'support_long_desc':
        'We continue to develop the Quran Diary app completely free and ad-free. If you would like to ensure the continuity of this project and contribute to its development, you can support us.',
    'support_footer':
        'Your support will be used for server costs and further development of the app.',
    'donation_tier_1': 'Support the App',
    'donation_tier_2': 'Contribute to Project',
    'donation_tier_3': 'Support Development',
    'donation_tier_default': 'Donate',
    'success_title': 'Thank You',
    'success_body':
        'Your support is very valuable to us. We will continue to develop the app with your contributions.',
    'secure_payment': 'Secure Payment & Anonymous Donation',
    'support_gold_subtitle': 'Support this Good Cause ✨',
    'prayer_method_title': 'Prayer Time Calculation Method',
    'prayer_method_subtitle': 'Which authority would you like to use?',
    'prayer_method_auto': 'Automatic (Recommended)',
    'prayer_method_auto_desc': 'Based on your location',
    'prayer_method_turkey': 'Turkey (Diyanet)',
    'prayer_method_mwl': 'Muslim World League (Europe/Global)',
    'prayer_method_isna': 'North America (ISNA)',
    'prayer_method_makkah': 'Makkah (Umm Al-Qura)',
    'prayer_method_egypt': 'Egypt (General Authority of Survey)',
    // Prayer Times Localization
    'prayer_fajr': 'Fajr',
    'prayer_sunrise': 'Sunrise',
    'prayer_dhuhr': 'Dhuhr',
    'prayer_asr': 'Asr',
    'prayer_maghrib': 'Maghrib',
    'prayer_isha': 'Isha',
    'time_remaining_sahur': 'TIME TO SUHOOR',
    'time_remaining_iftar': 'TIME TO IFTAR',
    'time_remaining_sunrise': 'TIME TO SUNRISE',
    'time_remaining_general': 'REMAINING TO',
    // Prayer Times
    'prayer_times_title': 'Imsakiye - Prayer Times', // Used during Ramadan
    'prayer_times_title_regular': 'Prayer Times', // Used outside Ramadan
    'table_date': 'Date',
    'loading': 'Loading...',
    'location_default': 'Your Location',
    // Prayer Notification Settings
    'prayer_notif_toggle': 'Prayer time reminders',
    'prayer_notif_desc': '15 minutes before each prayer',
    'prayer_notif_fajr': '15 minutes until Morning prayer 🕌',
    'prayer_notif_dhuhr': '15 minutes until Dhuhr prayer 🕌',
    'prayer_notif_asr': '15 minutes until Asr prayer 🕌',
    'prayer_notif_maghrib': '15 minutes until Maghrib prayer 🕌',
    'prayer_notif_isha': '15 minutes until Isha prayer 🕌',
    'prayer_notif_test': 'Send Test Notification',
    'prayer_notif_test_sent': '✅ Test notification will arrive in 5 seconds!',
    // Reminders Section
    'reminders_section': 'Reminders',
    'verse_notif_toggle': 'Daily Verse Reminders',
    'prayer_notif_title': 'Prayer Time Reminders',
    // Prayer Times Disclaimer (About Section)
    'disclaimer_title': 'Prayer Times & Disclaimer',
    'disclaimer_content':
        'Prayer times are generated instantly using astronomical calculations based on your device\'s location. For Turkey, the criteria of the Presidency of Religious Affairs (Diyanet) are adopted.\n\nDisclaimer: Due to mathematical calculations and local geographical differences, deviations of ±1-2 minutes may occur. It is recommended to follow the local adhan or mosque times for caution, especially for Fasting.\n\nPrivacy: Your location data is processed locally solely for calculation purposes and is never stored on our servers or shared.',
  },
};

String t(String key) {
  return dictionary[GlobalSettings.currentLanguage]?[key] ?? key;
}
