import '../services/global_settings.dart';

final Map<String, Map<String, String>> dictionary = {
  'tr': {
    'app_name': 'Kuran Günlüğü',
    'slogan': 'Huzurla Oku',
    'splash_text': 'Bunlar hikmet dolu\nKitabın ayetleridir.',
    'today_ayah': 'GÜNÜN AYETİ',
    'save': 'Kaydet',
    'saved': 'Listemde',
    'share': 'Paylaş',
    'listen': 'Dinle',
    'stop': 'Durdur',
    'list_title': 'Listem',
    'list_empty': 'Henüz kaydedilmiş bir ayet yok.',
    'settings_title': 'Ayarlar',
    'language': 'Dil',
    'font_size': 'Yazı Boyutu',
    'size_small': 'Küçük',
    'size_medium': 'Orta',
    'size_large': 'Büyük',
    'added_msg': 'Listene kaydedildi ✅',
    'removed_msg': 'Listeden çıkarıldı',
    'premium_locked': 'Geçmiş Kilitli',
    'premium_desc': 'Daha eskiye gitmek için\nPremium üye olmalısınız.',
    'get_premium': "PREMIUM'A GEÇ",
    'go_today': 'Bugüne Dön',
    'prem_title': 'Premium Üyelik',
    'prem_active': 'Premium Üye 👑',
    'share_loading': 'Görüntü hazırlanıyor...',
    'prem_f1': 'Reklamsız Deneyim',
    'prem_f2': 'Sınırsız Geçmişe Erişim',
    'prem_f3': 'Özel Yazı Tipleri',
    'prem_f4': 'Geliştiriciye Destek',
    'prem_price': 'Yıllık Sadece 199.99 ₺',
    'prem_btn': 'ABONE OL',
    'prem_success': 'Tebrikler! Artık Premiumsunuz 🎉',
    'notif_title': 'Hayırlı Sabahlar ☀️',
    'notif_body': 'Bugünün ayeti seni bekliyor. Okumak ister misin?',
    'test_msg': 'Bildirimler başarıyla çalışıyor! 🚀',
    'note_title': 'Günlük Notum 📝',
    'note_hint': 'Bu ayet sana ne hissettirdi?',
    // ignore: equal_keys_in_map
    'save': 'Kaydet',
    'your_note': 'Notun:',
    'my_note': 'Notum:',
    'add_note': 'Not Ekle',
    'edit_note': 'Notu Düzenle',
    'notif_active': 'Bildirimler Aktif ✅',
    'notif_inactive': 'Bildirimler Kapalı 🔕',
    'notif_active_desc': 'Her gün ayetiniz cebinizde.',
    'notif_inactive_desc':
        'Günün ayetini kaçırmamak için lütfen bildirimleri açın.',
    'turn_on': 'AÇ',
    'reciter_title': 'Seslendiren Hafız',
    'selected_reciter': 'Seçili Hafız',
    'select_reciter_title': 'Hafız Seçimi',
  },
  'en': {
    'app_name': 'Quran Diary',
    'slogan': 'Read with Peace',
    'splash_text': 'These are verses of the\nWise Book.',
    'today_ayah': 'VERSE OF THE DAY',
    'save': 'Save',
    'saved': 'Saved',
    'share': 'Share',
    'listen': 'Listen',
    'stop': 'Stop',
    'list_title': 'My List',
    'list_empty': 'No saved verses yet.',
    'settings_title': 'Settings',
    'language': 'Language',
    'font_size': 'Font Size',
    'size_small': 'Small',
    'size_medium': 'Medium',
    'size_large': 'Large',
    'added_msg': 'Saved to your list ✅',
    'removed_msg': 'Removed from list',
    'premium_locked': 'History Locked',
    'premium_desc': 'You need Premium membership\nto go further back.',
    'get_premium': 'GET PREMIUM',
    'go_today': 'Go to Today',
    'prem_title': 'Premium Membership',
    'prem_active': 'Premium Member 👑',
    'share_loading': 'Preparing image...',
    'prem_f1': 'Ad-Free Experience',
    'prem_f2': 'Unlimited History Access',
    'prem_f3': 'Custom Fonts',
    'prem_f4': 'Support Development',
    'prem_price': 'Yearly Only \$19.99',
    'prem_btn': 'SUBSCRIBE NOW',
    'prem_success': 'Congrats! You are Premium 🎉',
    'notif_title': 'Good Morning ☀️',
    'notif_body': 'Verse of the day is ready. Would you like to read?',
    'test_msg': 'Notifications work perfectly! 🚀',
    'note_title': 'My Daily Note 📝',
    'note_hint': 'How did this verse make you feel?',
    // ignore: equal_keys_in_map
    'save': 'SAVE',
    'your_note': 'Your Note:',
    'my_note': 'My Note:',
    'add_note': 'Add Note',
    'edit_note': 'Edit Note',
    'notif_active': 'Notifications Active ✅',
    'notif_inactive': 'Notifications Off 🔕',
    'notif_active_desc': 'Daily verse is in your pocket.',
    'notif_inactive_desc':
        'Please turn on notifications to not miss the daily verse.',
    'turn_on': 'TURN ON',
    'reciter_title': 'Reciter',
    'selected_reciter': 'Selected Reciter',
    'select_reciter_title': 'Select Reciter',
  },
};

String t(String key) {
  return dictionary[GlobalSettings.currentLanguage]?[key] ?? key;
}
